using Entities.ResponseObject;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace BadmintonMatching.Controllers
{
    [Route("api/wards")]
    [ApiController]
    public class WardController : ControllerBase
    {
        private List<Ward> wards = new List<Ward>
    {
        new Ward { Id = 1, Name = "Phường Bến Nghé", DistrictId = 1 },
        new Ward { Id = 2, Name = "Phường Cô Giang", DistrictId = 1 },
        new Ward { Id = 3, Name = "Phường Bến Thành", DistrictId = 1 },
        new Ward { Id = 4, Name = "Phường Cầu Kho", DistrictId = 1 },
        new Ward { Id = 5, Name = "Phường Đa Kao", DistrictId = 1 },
        new Ward { Id = 6, Name = "Phường Cầu Ông Lãnh", DistrictId = 1 },
        new Ward { Id = 7, Name = "Phường Nguyễn Thái Bình", DistrictId = 1 },
        new Ward { Id = 8, Name = "Phường Nguyễn Cư Trinh", DistrictId = 1 },
        new Ward { Id = 9, Name = "Phường Phạm Ngũ Lão", DistrictId = 1 },
        new Ward { Id = 10, Name = "Phường Tân Định", DistrictId = 1 },
        new Ward { Id = 11, Name = "Phường 1 ", DistrictId = 2 },
        new Ward { Id = 12, Name = "Phường 2", DistrictId = 2 },
        new Ward { Id = 13, Name = "Phường 3", DistrictId = 2 },
        new Ward { Id = 14, Name = "Phường 4", DistrictId = 2 },
        new Ward { Id = 15, Name = "Phường 5", DistrictId = 2 },
        new Ward { Id = 16, Name = "Phường 9", DistrictId = 2 },
        new Ward { Id = 17, Name = "Phường 10", DistrictId = 2 },
        new Ward { Id = 18, Name = "Phường 11", DistrictId = 2 },
        new Ward { Id = 19, Name = "Phường 12", DistrictId = 2 },
        new Ward { Id = 20, Name = "Phường 13", DistrictId = 2 },
        new Ward { Id = 21, Name = "Phường 14", DistrictId = 2 },
        new Ward { Id = 22, Name = "Phường Võ Thị Sáu", DistrictId = 2 },
        new Ward { Id = 23, Name = "Phường 1", DistrictId = 3 },
        new Ward { Id = 24, Name = "Phường 2", DistrictId = 3 },
        new Ward { Id = 25, Name = "Phường 3", DistrictId = 3 },
        new Ward { Id = 26, Name = "Phường 4", DistrictId = 3 },
        new Ward { Id = 27, Name = "Phường 6", DistrictId = 3 },
        new Ward { Id = 28, Name = "Phường 8", DistrictId = 3 },
        new Ward { Id = 29, Name = "Phường 9", DistrictId = 3 },
        new Ward { Id = 30, Name = "Phường 10", DistrictId = 3 },
        new Ward { Id = 31, Name = "Phường 13", DistrictId = 3 },
        new Ward { Id = 32, Name = "Phường 14", DistrictId = 3 },
        new Ward { Id = 33, Name = "Phường 15", DistrictId = 3 },
        new Ward { Id = 34, Name = "Phường 16", DistrictId = 3 },
        new Ward { Id = 35, Name = "Phường 18", DistrictId = 3 },
        new Ward { Id = 36, Name = "Phường 1", DistrictId = 4 },
        new Ward { Id = 37, Name = "Phường 2", DistrictId = 4 },
        new Ward { Id = 38, Name = "Phường 3", DistrictId = 4 },
        new Ward { Id = 39, Name = "Phường 4", DistrictId = 4 },
        new Ward { Id = 40, Name = "Phường 5", DistrictId = 4 },
        new Ward { Id = 41, Name = "Phường 6", DistrictId = 4 },
        new Ward { Id = 42, Name = "Phường 7", DistrictId = 4 },
        new Ward { Id = 43, Name = "Phường 8", DistrictId = 4 },
        new Ward { Id = 44, Name = "Phường 9", DistrictId = 4 },
        new Ward { Id = 45, Name = "Phường 10", DistrictId = 4 },
        new Ward { Id = 46, Name = "Phường 11", DistrictId = 4 },
        new Ward { Id = 47, Name = "Phường 12", DistrictId = 4 },
        new Ward { Id = 48, Name = "Phường 13", DistrictId = 4 },
        new Ward { Id = 49, Name = "Phường 14", DistrictId = 4 },
        new Ward { Id = 50, Name = "Phường 15", DistrictId = 4 },
        new Ward { Id = 51, Name = "Phường 1", DistrictId = 5 },
        new Ward { Id = 52, Name = "Phường 2", DistrictId = 5 },
        new Ward { Id = 53, Name = "Phường 3", DistrictId = 5 },
        new Ward { Id = 54, Name = "Phường 4", DistrictId = 5 },
        new Ward { Id = 55, Name = "Phường 5", DistrictId = 5 },
        new Ward { Id = 56, Name = "Phường 6", DistrictId = 5 },
        new Ward { Id = 57, Name = "Phường 7", DistrictId = 5 },
        new Ward { Id = 58, Name = "Phường 8", DistrictId = 5 },
        new Ward { Id = 59, Name = "Phường 9", DistrictId = 5 },
        new Ward { Id = 60, Name = "Phường 10", DistrictId = 5 },
        new Ward { Id = 61, Name = "Phường 11", DistrictId = 5 },
        new Ward { Id = 62, Name = "Phường 12", DistrictId = 5 },
        new Ward { Id = 63, Name = "Phường 13", DistrictId = 5 },
        new Ward { Id = 64, Name = "Phường 14", DistrictId = 5 },
        new Ward { Id = 65, Name = "Phường Phú Mỹ", DistrictId = 6 },
        new Ward { Id = 66, Name = "Phường Phú Thuận", DistrictId = 6 },
        new Ward { Id = 67, Name = "Phường Tân Phú", DistrictId = 6 },
        new Ward { Id = 68, Name = "Phường Tân Thuận Đông", DistrictId = 6 },
        new Ward { Id = 69, Name = "Phường Bình Thuận", DistrictId = 6 },
        new Ward { Id = 70, Name = "Phường Tân Thuận Tây", DistrictId = 6 },
        new Ward { Id = 71, Name = "Phường Tân Kiểng", DistrictId = 6 },
        new Ward { Id = 72, Name = "Phường Tân Quy", DistrictId = 6 },
        new Ward { Id = 73, Name = "Phường Tân Phong", DistrictId = 6 },
        new Ward { Id = 74, Name = "Phường Tân Hưng", DistrictId = 6 },
        new Ward { Id = 75, Name = "Phường 1", DistrictId = 7 },
        new Ward { Id = 76, Name = "Phường 2", DistrictId = 7 },
        new Ward { Id = 77, Name = "Phường 3", DistrictId = 7 },
        new Ward { Id = 78, Name = "Phường 4", DistrictId = 7 },
        new Ward { Id = 79, Name = "Phường 5", DistrictId = 7 },
        new Ward { Id = 80, Name = "Phường 6", DistrictId = 7 },
        new Ward { Id = 81, Name = "Phường 7", DistrictId = 7 },
        new Ward { Id = 82, Name = "Phường 8", DistrictId = 7 },
        new Ward { Id = 83, Name = "Phường 9", DistrictId = 7 },
        new Ward { Id = 84, Name = "Phường 10", DistrictId = 7 },
        new Ward { Id = 85, Name = "Phường 11", DistrictId = 7 },
        new Ward { Id = 86, Name = "Phường 12", DistrictId = 7 },
        new Ward { Id = 87, Name = "Phường 13", DistrictId = 7 },
        new Ward { Id = 88, Name = "Phường 14", DistrictId = 7 },
        new Ward { Id = 89, Name = "Phường 15", DistrictId = 7 },
        new Ward { Id = 90, Name = "Phường 16", DistrictId = 7 },
        new Ward { Id = 91, Name = "Phường 1", DistrictId = 8 },
        new Ward { Id = 92, Name = "Phường 2", DistrictId = 8 },
        new Ward { Id = 93, Name = "Phường 3", DistrictId = 8 },
        new Ward { Id = 94, Name = "Phường 4", DistrictId = 8 },
        new Ward { Id = 95, Name = "Phường 5", DistrictId = 8 },
        new Ward { Id = 96, Name = "Phường 6", DistrictId = 8 },
        new Ward { Id = 97, Name = "Phường 7", DistrictId = 8 },
        new Ward { Id = 98, Name = "Phường 8", DistrictId = 8 },
        new Ward { Id = 99, Name = "Phường 9", DistrictId = 8 },
        new Ward { Id = 100, Name = "Phường 10", DistrictId = 8 },
        new Ward { Id = 101, Name = "Phường 11", DistrictId = 8 },
        new Ward { Id = 102, Name = "Phường 12", DistrictId = 8 },
        new Ward { Id = 103, Name = "Phường 13", DistrictId = 8 },
        new Ward { Id = 104, Name = "Phường 14", DistrictId = 8 },
        new Ward { Id = 105, Name = "Phường 15", DistrictId = 8 },
        new Ward { Id = 106, Name = "Phường 1", DistrictId = 9 },
        new Ward { Id = 107, Name = "Phường 2", DistrictId = 9 },
        new Ward { Id = 108, Name = "Phường 3", DistrictId = 9 },
        new Ward { Id = 109, Name = "Phường 4", DistrictId = 9 },
        new Ward { Id = 110, Name = "Phường 5", DistrictId = 9 },
        new Ward { Id = 111, Name = "Phường 6", DistrictId = 9 },
        new Ward { Id = 112, Name = "Phường 7", DistrictId = 9 },
        new Ward { Id = 113, Name = "Phường 8", DistrictId = 9 },
        new Ward { Id = 114, Name = "Phường 9", DistrictId = 9 },
        new Ward { Id = 115, Name = "Phường 10", DistrictId = 9 },
        new Ward { Id = 116, Name = "Phường 11", DistrictId = 9 },
        new Ward { Id = 117, Name = "Phường 12", DistrictId = 9 },
        new Ward { Id = 118, Name = "Phường 13", DistrictId = 9 },
        new Ward { Id = 119, Name = "Phường 14", DistrictId = 9 },
        new Ward { Id = 120, Name = "Phường 15", DistrictId = 9 },
        new Ward { Id = 121, Name = "Phường 16", DistrictId = 9 },
        new Ward { Id = 122, Name = "Phường An Phú Đông", DistrictId = 10 },
        new Ward { Id = 122, Name = "Phường Đông Hưng Thuận", DistrictId = 10 },
        new Ward { Id = 122, Name = "Phường Hiệp Thành", DistrictId = 10 },
        new Ward { Id = 122, Name = "Phường Tân Chánh Hiệp", DistrictId = 10 },
        new Ward { Id = 123, Name = "Phường Tân Hưng Thuận", DistrictId = 10 },
        new Ward { Id = 124, Name = "Phường Tân Thới Hiệp", DistrictId = 10 },
        new Ward { Id = 125, Name = "Phường Tân Thới Nhất", DistrictId = 10 },
        new Ward { Id = 126, Name = "Phường Thạnh Lộc", DistrictId = 10 },
        new Ward { Id = 127, Name = "Phường Thạnh Xuân", DistrictId = 10 },
        new Ward { Id = 128, Name = "Phường Thới An", DistrictId = 10 },
        new Ward { Id = 129, Name = "Phường Trung Mỹ Tây", DistrictId = 10 },
        new Ward { Id = 130, Name = "Phường 1", DistrictId = 11 },
        new Ward { Id = 131, Name = "Phường 2", DistrictId = 11 },
        new Ward { Id = 132, Name = "Phường 3", DistrictId = 11 },
        new Ward { Id = 133, Name = "Phường 5", DistrictId = 11 },
        new Ward { Id = 134, Name = "Phường 6", DistrictId = 11 },
        new Ward { Id = 135, Name = "Phường 7", DistrictId = 11 },
        new Ward { Id = 136, Name = "Phường 11", DistrictId = 11 },
        new Ward { Id = 137, Name = "Phường 12", DistrictId = 11 },
        new Ward { Id = 138, Name = "Phường 13", DistrictId = 11 },
        new Ward { Id = 139, Name = "Phường 14", DistrictId = 11 },
        new Ward { Id = 140, Name = "Phường 15", DistrictId = 11 },
        new Ward { Id = 141, Name = "Phường 17", DistrictId = 11 },
        new Ward { Id = 142, Name = "Phường 19", DistrictId = 11 },
        new Ward { Id = 143, Name = "Phường 21", DistrictId = 11 },
        new Ward { Id = 144, Name = "Phường 22", DistrictId = 11 },
        new Ward { Id = 145, Name = "Phường 24", DistrictId = 11 },
        new Ward { Id = 146, Name = "Phường 25", DistrictId = 11 },
        new Ward { Id = 147, Name = "Phường 26", DistrictId = 11 },
        new Ward { Id = 148, Name = "Phường 27", DistrictId = 11 },
        new Ward { Id = 149, Name = "Phường 28", DistrictId = 11 },
        new Ward { Id = 150, Name = "Phường An Lạc A", DistrictId = 12 },
        new Ward { Id = 151, Name = "Phường An Lạc", DistrictId = 12 },
        new Ward { Id = 152, Name = "Phường Bình Hưng Hòa", DistrictId = 12 },
        new Ward { Id = 153, Name = "Phường Bình Hưng Hòa A", DistrictId = 12 },
        new Ward { Id = 154, Name = "Phường Bình Hưng Hòa B", DistrictId = 12 },
        new Ward { Id = 155, Name = "Phường Bình Trị Đông", DistrictId = 12 },
        new Ward { Id = 156, Name = "Phường Bình Trị Đông A", DistrictId = 12 },
        new Ward { Id = 157, Name = "Phường Bình Trị Đông B", DistrictId = 12 },
        new Ward { Id = 158, Name = "Phường Tân Tạo", DistrictId = 12 },
        new Ward { Id = 159, Name = "Phường Tân Tạo A", DistrictId = 12 },
        new Ward { Id = 160, Name = "Phường 1", DistrictId = 13 },
        new Ward { Id = 161, Name = "Phường 2", DistrictId = 13 },
        new Ward { Id = 162, Name = "Phường 3", DistrictId = 13 },
        new Ward { Id = 163, Name = "Phường 4", DistrictId = 13 },
        new Ward { Id = 164, Name = "Phường 5", DistrictId = 13 },
        new Ward { Id = 165, Name = "Phường 6", DistrictId = 13 },
        new Ward { Id = 166, Name = "Phường 7", DistrictId = 13 },
        new Ward { Id = 167, Name = "Phường 11", DistrictId = 13 },
        new Ward { Id = 168, Name = "Phường 12", DistrictId = 13 },
        new Ward { Id = 169, Name = "Phường 13", DistrictId = 13 },
        new Ward { Id = 170, Name = "Phường 14", DistrictId = 13 },
        new Ward { Id = 171, Name = "Phường 15", DistrictId = 13 },
        new Ward { Id = 172, Name = "Phường Hiệp Tân", DistrictId = 14 },
        new Ward { Id = 173, Name = "Phường Hòa Thạnh", DistrictId = 14 },
        new Ward { Id = 174, Name = "Phường Phú Thạnh", DistrictId = 14 },
        new Ward { Id = 175, Name = "Phường Phú Thọ Hòa", DistrictId = 14 },
        new Ward { Id = 176, Name = "Phường Phú Trung", DistrictId = 14 },
        new Ward { Id = 177, Name = "Phường Sơn Kỳ", DistrictId = 14 },
        new Ward { Id = 178, Name = "Phường Tân Quý", DistrictId = 14 },
        new Ward { Id = 179, Name = "Phường Tân Sơn Nhì", DistrictId = 14 },
        new Ward { Id = 180, Name = "Phường Tân Thành", DistrictId = 14 },
        new Ward { Id = 181, Name = "Phường Tân Thới Hòa", DistrictId = 14 },
        new Ward { Id = 182, Name = "Phường Tây Thạnh", DistrictId = 14 },
        new Ward { Id = 183, Name = "Phường 1", DistrictId = 15 },
        new Ward { Id = 184, Name = "Phường 3", DistrictId = 15 },
        new Ward { Id = 185, Name = "Phường 4", DistrictId = 15 },
        new Ward { Id = 186, Name = "Phường 5", DistrictId = 15 },
        new Ward { Id = 187, Name = "Phường 6", DistrictId = 15 },
        new Ward { Id = 188, Name = "Phường 7", DistrictId = 15 },
        new Ward { Id = 189, Name = "Phường 8", DistrictId = 15 },
        new Ward { Id = 190, Name = "Phường 9", DistrictId = 15 },
        new Ward { Id = 191, Name = "Phường 10", DistrictId = 15 },
        new Ward { Id = 192, Name = "Phường 11", DistrictId = 15 },
        new Ward { Id = 193, Name = "Phường 12", DistrictId = 15 },
        new Ward { Id = 194, Name = "Phường 13", DistrictId = 15 },
        new Ward { Id = 195, Name = "Phường 14", DistrictId = 15 },
        new Ward { Id = 196, Name = "Phường 15", DistrictId = 15 },
        new Ward { Id = 197, Name = "Phường 16", DistrictId = 15 },
        new Ward { Id = 198, Name = "Phường 17", DistrictId = 15 },
        new Ward { Id = 199, Name = "Phường 1", DistrictId = 16 },
        new Ward { Id = 200, Name = "Phường 2", DistrictId = 16 },
        new Ward { Id = 201, Name = "Phường 3", DistrictId = 16 },
        new Ward { Id = 202, Name = "Phường 4", DistrictId = 16 },
        new Ward { Id = 203, Name = "Phường 5", DistrictId = 16 },
        new Ward { Id = 204, Name = "Phường 7", DistrictId = 16 },
        new Ward { Id = 205, Name = "Phường 8", DistrictId = 16 },
        new Ward { Id = 206, Name = "Phường 9", DistrictId = 16 },
        new Ward { Id = 207, Name = "Phường 10", DistrictId = 16 },
        new Ward { Id = 208, Name = "Phường 11", DistrictId = 16 },
        new Ward { Id = 209, Name = "Phường 13", DistrictId = 16 },
        new Ward { Id = 210, Name = "Phường 15", DistrictId = 16 },
        new Ward { Id = 211, Name = "Phường 17", DistrictId = 16 },
        new Ward { Id = 212, Name = "Xã Bà Điểm", DistrictId = 17 },
        new Ward { Id = 213, Name = "Xã Nhị Bình", DistrictId = 17 },
        new Ward { Id = 214, Name = "Xã Tân Thới Nhì", DistrictId = 17 },
        new Ward { Id = 215, Name = "Xã Thới Tam Thôn", DistrictId = 17 },
        new Ward { Id = 216, Name = "Xã Xuân Thới Đông", DistrictId = 17 },
        new Ward { Id = 217, Name = "Xã Xuân Thới Thượng", DistrictId = 17 },
        new Ward { Id = 218, Name = "Xã Đông Thạnh", DistrictId = 17 },
        new Ward { Id = 219, Name = "Xã Tân Hiệp", DistrictId = 17 },
        new Ward { Id = 220, Name = "Xã Tân Xuân", DistrictId = 17 },
        new Ward { Id = 221, Name = "Xã Trung Chánh", DistrictId = 17 },
        new Ward { Id = 222, Name = "Xã Xuân Thới Sơn", DistrictId = 17 },
        new Ward { Id = 223, Name = "Thị Trấn HM", DistrictId = 17 },
        new Ward { Id = 224, Name = "Xã Tân Phú Trung", DistrictId = 18 },
        new Ward { Id = 225, Name = "Xã Tân Thông Hội", DistrictId = 18 },
        new Ward { Id = 226, Name = "Xã Tân An Hội", DistrictId = 18 },
        new Ward { Id = 227, Name = "Xã Phước Hiệp", DistrictId = 18 },
        new Ward { Id = 228, Name = "Xã Phước Thạnh", DistrictId = 18 },
        new Ward { Id = 229, Name = "Xã Thái Mỹ", DistrictId = 18 },
        new Ward { Id = 230, Name = "Xã Trung Lập Hạ", DistrictId = 18 },
        new Ward { Id = 231, Name = "Xã Trung Lập Thượng", DistrictId = 18 },
        new Ward { Id = 232, Name = "Xã An Nhơn Tây", DistrictId = 18 },
        new Ward { Id = 233, Name = "Xã An Phú", DistrictId = 18 },
        new Ward { Id = 234, Name = "Xã Phú Mỹ Hưng", DistrictId = 18 },
        new Ward { Id = 235, Name = "Xã Nhuận Đức", DistrictId = 18 },
        new Ward { Id = 236, Name = "Xã Phạm Văn Cội", DistrictId = 18 },
        new Ward { Id = 237, Name = "Xã Phú Hòa Đông", DistrictId = 18 },
        new Ward { Id = 238, Name = "Xã Tân Thạnh Tây", DistrictId = 18 },
        new Ward { Id = 239, Name = "Xã Trung An", DistrictId = 18 },
        new Ward { Id = 240, Name = "Xã Hòa Phú", DistrictId = 18 },
        new Ward { Id = 241, Name = "Xã Bình Mỹ", DistrictId = 18 },
        new Ward { Id = 242, Name = "Xã Tân Thạnh Đông", DistrictId = 18 },
        new Ward { Id = 243, Name = "Xã Phước Vĩnh An", DistrictId = 18 },
        new Ward { Id = 244, Name = "Thị trấn Nhà Bè", DistrictId = 19 },
        new Ward { Id = 245, Name = "Xã Phước Kiển", DistrictId = 19 },
        new Ward { Id = 246, Name = "Xã Phước Lộc", DistrictId = 19 },
        new Ward { Id = 247, Name = "Xã Nhơn Đức", DistrictId = 19 },
        new Ward { Id = 248, Name = "Xã Phú Xuân", DistrictId = 19 },
        new Ward { Id = 249, Name = "Xã Long Thới", DistrictId = 19 },
        new Ward { Id = 250, Name = "Xã Hiệp Phước", DistrictId = 19 },
        new Ward { Id = 251, Name = "Thị trấn Tân Túc", DistrictId = 20 },
        new Ward { Id = 252, Name = "Xã An Phú Tây", DistrictId = 20 },
        new Ward { Id = 253, Name = "Xã Bình Chánh", DistrictId = 20 },
        new Ward { Id = 254, Name = "Xã Bình Hưng", DistrictId = 20 },
        new Ward { Id = 255, Name = "Xã Bình Lợi", DistrictId = 20 },
        new Ward { Id = 256, Name = "Xã Đa Phước", DistrictId = 20 },
        new Ward { Id = 257, Name = "Xã Hưng Long", DistrictId = 20 },
        new Ward { Id = 258, Name = "Xã Lê Minh Xuân", DistrictId = 20 },
        new Ward { Id = 259, Name = "Xã Phạm Văn Hai", DistrictId = 20 },
        new Ward { Id = 260, Name = "Xã Phong Phú", DistrictId = 20 },
        new Ward { Id = 261, Name = "Xã Quy Đức", DistrictId = 20 },
        new Ward { Id = 262, Name = "Xã Tân Kiên", DistrictId = 20 },
        new Ward { Id = 263, Name = "Xã Tân Nhựt", DistrictId = 20 },
        new Ward { Id = 264, Name = "Xã Tân Quý Tây", DistrictId = 20 },
        new Ward { Id = 265, Name = "Xã Vĩnh Lộc A", DistrictId = 20 },
        new Ward { Id = 266, Name = "Xã Vĩnh Lộc B", DistrictId = 20 },
        new Ward { Id = 267, Name = "Xã An Thới Đông", DistrictId = 21 },
        new Ward { Id = 268, Name = "Xã Bình Khánh", DistrictId = 21 },
        new Ward { Id = 269, Name = "Xã Cần Thạnh", DistrictId = 21 },
        new Ward { Id = 270, Name = "Xã Long Hòa", DistrictId = 21 },
        new Ward { Id = 271, Name = "Xã Lý Nhơn", DistrictId = 21 },
        new Ward { Id = 272, Name = "Xã Tam Thôn Hiệp", DistrictId = 21 },
        new Ward { Id = 273, Name = "Xã Thạnh An", DistrictId = 21 },
        new Ward { Id = 274, Name = "Phường Linh Chiểu", DistrictId = 22 },
        new Ward { Id = 275, Name = "Phường Bình Thọ", DistrictId = 22 },
        new Ward { Id = 276, Name = "Phường Linh Tây", DistrictId = 22 },
        new Ward { Id = 277, Name = "Phường Linh Trung", DistrictId = 22 },
        new Ward { Id = 278, Name = "Phường Linh Xuân", DistrictId = 22 },
        new Ward { Id = 279, Name = "Phường Bình Chiểu", DistrictId = 22 },
        new Ward { Id = 280, Name = "Phường Hiệp Bình Chánh", DistrictId = 22 },
        new Ward { Id = 281, Name = "Phường Hiệp Bình Phước", DistrictId = 22 },
        new Ward { Id = 282, Name = "Phường Tam Bình", DistrictId = 22 },
        new Ward { Id = 283, Name = "Phường Tam Phú", DistrictId = 22 },
        new Ward { Id = 284, Name = "Phường Linh Đông", DistrictId = 22 },
        new Ward { Id = 285, Name = "Phường Trường Thọ", DistrictId = 22 },
        new Ward { Id = 286, Name = "Phường Hiệp Phú", DistrictId = 23 },
        new Ward { Id = 287, Name = "Phường Long Bình", DistrictId = 23 },
        new Ward { Id = 288, Name = "Phường Long Phước", DistrictId = 23 },
        new Ward { Id = 289, Name = "Phường Long Thạnh Mỹ", DistrictId = 23 },
        new Ward { Id = 290, Name = "Phường Long Trường", DistrictId = 23 },
        new Ward { Id = 291, Name = "Phường Phú Hữu", DistrictId = 23 },
        new Ward { Id = 292, Name = "Phường Phước Bình", DistrictId = 23 },
        new Ward { Id = 293, Name = "Phường Phước Long A,", DistrictId = 23 },
        new Ward { Id = 294, Name = "Phường Phước Long B", DistrictId = 23 },
        new Ward { Id = 295, Name = "Phường Tân Phú", DistrictId = 23 },
        new Ward { Id = 296, Name = "Phường Tăng Nhơn Phú A", DistrictId = 23 },
        new Ward { Id = 297, Name = "Phường Tăng Nhơn Phú B", DistrictId = 23 },
        new Ward { Id = 298, Name = "Phường Trường Thạnh", DistrictId = 23 },
        new Ward { Id = 299, Name = "Phường An Khánh", DistrictId = 24 },
        new Ward { Id = 300, Name = "Phường An Lợi Đông", DistrictId = 24 },
        new Ward { Id = 301, Name = "Phường An Phú", DistrictId = 24 },
        new Ward { Id = 302, Name = "Phường Bình Khánh", DistrictId = 24 },
        new Ward { Id = 303, Name = "Phường Bình Trưng Đông", DistrictId = 24 },
        new Ward { Id = 304, Name = "Phường Bình Trưng Tây", DistrictId = 24 },
        new Ward { Id = 305, Name = "Phường Cát Lái", DistrictId = 24 },
        new Ward { Id = 306, Name = "Phường Thạnh Mỹ Lợi", DistrictId = 24 },
        new Ward { Id = 307, Name = "Phường Thảo Điền", DistrictId = 24 },
        new Ward { Id = 308, Name = "Phường Thủ Thiêm", DistrictId = 24 },
        new Ward { Id = 309, Name = "Phường Bình An", DistrictId = 24 },
        
        
        // Thêm thông tin về các phường khác
    };

        [HttpGet]
        [ProducesResponseType(typeof(SuccessObject<List<Ward>>), 200)]

        public IActionResult GetWards()
        {
            return Ok(new SuccessObject<List<Ward>> { Data = wards, Message = Message.SuccessMsg });
        }

        [HttpGet("{id}")]
        [ProducesResponseType(typeof(SuccessObject<Ward>), 200)]

        public IActionResult GetWard(int id)
        {
            var ward = wards.FirstOrDefault(w => w.Id == id);
            if (ward == null)
            {
                return NotFound();
            }
            return Ok(new SuccessObject<Ward> { Data = ward, Message = Message.SuccessMsg });
        }

        [HttpGet("district/{districtId}")]
        [ProducesResponseType(typeof(SuccessObject<List<Ward>>), 200)]

        public IActionResult GetDistrictsInCity(int districtId)
        {
            // Lọc danh sách quận dựa trên cityId
            var cityDistricts = wards.Where(d => d.DistrictId == districtId).ToList();
            return Ok(new SuccessObject<List<Ward>> { Data = cityDistricts, Message = Message.SuccessMsg });
        }
    }
}
